name: Oertel Architects
favicon: null
layout_spectrum: 0
typography_spectrum: 0.74241
title: Oertel Architects home page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#181d20'
    - '#a1a2a4'
    - '#cdcfce'
    - '#6f7374'
    - '#545859'
  brandStrength: 0.4375
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0.25
purpose: []
