name: Oertel Architects
favicon: null
layout_spectrum: 0.21468663937412202
typography_spectrum: 0.25794454966671765
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.21181686595082283
  lightness: 0.8681721840985119
  saturation: 0.061889288714155555
  rhythmicContrast: 0.10604280629195273
purpose: []
